### ISSUE TITLE
Stuck on ember-data 2.13

### ISSUE THREAD

**Issue by kategengler** [emberobserver/client#104]
I had to put ember-data back down to 2.13 because any version >= 2.14  (tested 3.0, ember-data master as of 3/5/2018) causes a double-render error about modifying `sortedTopLevelCategories` twice in a single render, found in category-finder component. Even if all sorting, filtering, etc is removed, the problem persists. 

The error does not happen in tests, only when pointing to production API, either running locally or using the proxy to emberobserver.com. 

Happens when visiting the root path, and often only on the second reload. There is NO visible problem in production but it makes development unusable. 

To reproduce:
* `yarn upgrade ember-data --latest`
* Run `ember s`
* Load '/' in the browser
* Open devtools console
* Reload to see the error

**Comment by kaermorchen** [comment]
I try to reproduce (step by step) and all tests are green, but application doesn't have any models. 

![2018-05-11_20-12-54](https://user-images.githubusercontent.com/11972062/39937354-1a8de24c-5558-11e8-9780-9121799b1c85.png)

Do I something wrong?

```
    "ember-data": "~3.1.1",
```

**Comment by kaermorchen** [comment]
Looks like the problem with links in relationships of category model.

Check this [commit](https://github.com/kaermorchen/client/commit/45f603f235abd7d724d15a46a84cdc73b22818e5#diff-0617019b3e365aee57fb3492101f579f)

Index page don't has any errors. But has too much warnings like `WARNING: You pushed a record of type 'category' with a relationship 'parent' configured as 'async: false'. You've included a link but no primary data, this may be an error in your payload.`

I removed links and add `data` field. It is a bad hack-fix and should be fix on backend side.

**Comment by kategengler** [comment]
The backend is using the jsonapi-resources gem, latest version, to provide the API. 

Those warnings don't hurt anything (hence _may_ be an error). 

I believe there is a change in ember-data post 2.13 that causes the issue I found.

**Comment by kaermorchen** [comment]
> I believe there is a change in ember-data post 2.13 that causes the issue I found.

I agree.

> The backend is using the jsonapi-resources gem, latest version, to provide the API.

Can option [always_include_linkage_data](http://jsonapi-resources.com/v0.9/guide/resources.html#Relationships) help us?

**Comment by kategengler** [comment]
Tried out ember-data 3.2. I didn't see this problem but instead, on the index page, it attempts to load the `parent` relationship for each category, even though that relationship is marked as `async: false`
