### ISSUE TITLE
Thinks github repo is invalid, but displays proper readme and url???

### ISSUE THREAD

**Issue by elwayman02** [emberobserver/client#106]
See example: https://emberobserver.com/addons/ember-interactivity

<img width="1321" alt="ember-interactivity_-_ember_observer" src="https://user-images.githubusercontent.com/1325482/37312040-b91a401c-2606-11e8-9a22-c7e0b266b2f7.png">

**Comment by elwayman02** [comment]
The issue seems to have resolved itself since I posted it, possibly when it detected a new commit this afternoon? Perhaps there is a bug where EmberObserver does not detect the Github info once a score has been posted, until there are new commits made to the addon's repo?

**Comment by kategengler** [comment]
Nah, @pgengler fixed it by hand 😆 

But he also has a fix for the root cause, which was a backend bug in the translation of repo url to what we need to fetch from github.

**Comment by elwayman02** [comment]
Thank you!
