### ISSUE TITLE
Searching find addon only by addon name

### ISSUE THREAD

**Issue by kaermorchen** [emberobserver/client#107]
I noticed, if an addon has keyword in description or keywords fields of package.json, it won't be show in result, but if the addon has keyword in the name, it will.

Maybe best result of searching will be if to use description or keywords fields too.

**Comment by kategengler** [comment]
The search on the main page emberobserver.com does search description. The search in the header isn't really a search, but a jump-to-addon with the ability to trigger a full search. The main search can also search the full text of Readme.
