### ISSUE TITLE
Update score?

### ISSUE THREAD

**Issue by j15e** [emberobserver/client#12]
Hello,

I see a notice on my addon `New versions of this addon have been released since this review was undertaken.` which was on april 24th ; is there a way to trigger a new review?

http://emberobserver.com/addons/ember-meta-meta

Thanks

**Comment by kategengler** [comment]
Hi, 

The reviews are currently manual (we're working on a way for them to be self-reported), and we usually get to updated addons within 2-3 days. However I've been on vacation and so I'm a bit behind. 

Best, 
Katie
