### ISSUE TITLE
Autofocus search on homepage load

### ISSUE THREAD

**Issue by samselikoff** [emberobserver/client#14]
I'm used to using emberaddons.com for initial addon discovery, but I like the autocomplete widget on emberobserver.com better.

Something that would be nice is if the search box auto focused after initial page load. to support maximum laziness :D I think this is one of those small things that could push more people to use emberobserver for initial discovery in addition to deep-dive searches.

**Comment by kategengler** [comment]
I definitely agree! Will do asap.

**Comment by nathanhammond** [comment]
@samselikoff This change was reverted in a recent release for reasons of accessibility. Setting focus to that field on first load interrupts the default expected behavior for assistive tech users.
