### ISSUE TITLE
site is down

### ISSUE THREAD

**Issue by efx** [emberobserver/client#140]
Seems like some 502 errors have caused the site render blank.
<img width="1428" alt="screen shot 2019-02-25 at 09 20 16" src="https://user-images.githubusercontent.com/472721/53343895-68e1c600-38df-11e9-8a98-03594cd10d67.png">

**Comment by pgengler** [comment]
Thanks for letting us know...should be back up now, and we'll check on why our monitoring is failing.

**Comment by Windvis** [comment]
I'm still getting the errors. I don't think it's fixed yet (or it happened again).
