### ISSUE TITLE
Sort buttons on category pages are broken

### ISSUE THREAD

**Issue by noahthorn** [emberobserver/client#183]
The default sort-by score works, but the "Name" and "Updated" don't switch to different sorts.

Replicated on Chromium and Firefox @ this link: [Authentication](https://emberobserver.com/categories/authentication).

**Comment by kategengler** [comment]
@noahthorn Good catch! It looks like there aren't any tests for this area. Any chance you'd like to investigate this issue or add some failing tests?

**Comment by noahthorn** [comment]
@kategengler I can give it a go!

**Comment by noahthorn** [comment]
The sort buttons get an error saying there is no action handler for sortBy.

This is the action handler in the relevant controller:
```javascript
// controllers/categories/show.js
@action
  sortBy(key) {
    this.set('addonSortKey', key);
  }
```
This same code used to be in the button's component js, but was underscored out and then removed at some point:
```javascript
// components/sort-option.js
@action
  _sortBy(key) {
    this.set('addonSortKey', key);
  }
```
The button itself is coded like `{{action @sortBy @key}}`, and I'm not sure how to get it to call the action in the controller rather than the broken one in the component's js.

**Comment by kategengler** [comment]
@noahthorn Thanks for looking into this. It looks like this functionality was broken when removing the use of a deprecated Ember API, `sendAction`. The arguments passed to the `SortOption` component for `@sortBy` were strings, which worked with `sendAction` but didn't work when it was modified. As you can see in the fix from @pgengler, passing the controller's action down into the component solved it.
