### ISSUE TITLE
Addons not reviewed yet should probably not have a red icon

### ISSUE THREAD

**Issue by sir-dunxalot** [emberobserver/client#2]
Hey, nice site!

It seems that newly published addons will suffer a disadvantage if they immediately start with 0-2 points because they haven't been reviewed yet.

Perhaps, if they start with a low score, the score icon could be gray instead of red to communicate the difference between a bad addon and a new addon?

**Comment by kategengler** [comment]
Yep - Not yet reviewed addons will soon have 'NA'

**Comment by kategengler** [comment]
Also addons explicitly stating that they are a WIP or incomplete will have 'WIP'

**Comment by kategengler** [comment]
It's done!

**Comment by sir-dunxalot** [comment]
Awesome! Thanks :)
