### ISSUE TITLE
web site not working in chrome/safari

### ISSUE THREAD

**Issue by danielspaniel** [emberobserver/client#20]
In chrome, ember observer does not work.  Errors in console ( if you want me to copy I can, but it's easy to see yourself ) 
Also in Safari, home page works, but not clicking on subcategory

**Comment by bianjp** [comment]
It also failed in Firefox.
But different error were reported in Chrome VS Firefox.

**Comment by pgengler** [comment]
This should be fixed now. ember-inflector and the `pluralize` helper stopped working (on production builds only) after upgrading to Ember 2.0. Should be working again now.

**Comment by danielspaniel** [comment]
Interestingly .. safari now works fine, but chrome still does this:

Error parsing 'integrity' attribute ('sha256-ZIyvu2zcvUZC2jBOPBYWO1ZQFe3TkKs8AXAPrRZvI04= sha512-j3rLn5GzcK4UvvoqWkB4N5XtaPIKWRLmqXyI0uwhlbnAILlywk7BUXbAji0uaXevYEIWt5e0rFfnhJYrITbnqw=='). The value must begin with 'ni:///'.

 a few times and leaves the page blank
