### ISSUE TITLE
All addons links broken

### ISSUE THREAD

**Issue by malcolm-3** [emberobserver/client#238]
No matter what addon package name I click on today.  I am getting the "Oops! We can't find what you were looking for." page.  Search and category listing appear to be working fine.  Just the addon pages appear to be broken.  I am getting the same behavior from Firefox and Chrome on my Linux machine. Chrome on my Android phone, and Chrome and Edge on my Windows machine.

Everything was working fine on Saturday July 15, 2023.

**Comment by kategengler** [comment]
Thanks for reporting! We broke this with a deploy this morning, will be fixing asap.

**Comment by kategengler** [comment]
Fixed!
