### ISSUE TITLE
Feature Request: Query Param to Filter Addon Data Set

### ISSUE THREAD

**Issue by jherdman** [emberobserver/client#25]
I use Alfred, and one feature I really like is the ability to set up custom queries. Here's a screenshot of a query for an npm package:

<img width="496" alt="screen shot 2015-09-18 at 5 49 45 pm" src="https://cloud.githubusercontent.com/assets/3300/9971916/af3fd0b4-5e2d-11e5-9d4a-49c4b4320572.png">

And here's how I have it set up:

<img width="592" alt="screen shot 2015-09-18 at 5 50 33 pm" src="https://cloud.githubusercontent.com/assets/3300/9971928/c9e70d38-5e2d-11e5-955b-ead73a8c5e54.png">

I'd really like to be able to do this with Ember Observer too. All I'd need is a query param, e.g. `http://emberobserver.com?q=trackjs`.

What do you think? Is this worth me spending some time to implement?

**Comment by Sinled** [comment]
+1 to this feature,
it would be handy to have addons search right in alfred

**Comment by kategengler** [comment]
emberobserver.com/?query=foo now works.

**Comment by jherdman** [comment]
You da best! Many thanks!!!
