### ISSUE TITLE
Addons fall out of sync with maintainers who change their email address

### ISSUE THREAD

**Issue by null-null-null** [emberobserver/client#27]
At least, I'm assuming that's what happened.

I have five addons on Ember Observer, two from after I changed by email address on github and npm to `null@ember.theater`, and three from before. If you visit one of the new ones (such as [ember-dynamic-stylesheets](http://emberobserver.com/addons/ember-dynamic-stylesheet)) and click the maintainers link, you'll see just the addons I've started since the email change. If you go to one of the older ones (such as [ember-keyboard](http://emberobserver.com/addons/ember-keyboard)) and click the maintainers link, you'll see the three older addons.

Again, I'm not sure this was caused by the email change, but it seems like a likely candidate. It's also worth noting that the url for the maintainer profile is the same in both cases: http://emberobserver.com/maintainers/nullnullnull. If you refresh on the page or visit it directly, you'll only see the oldest three addons.

I'm not really bothered by this, but thought I should bring it to your attention. Either way, thanks for all your work on this!

**Comment by kategengler** [comment]
Thanks for bringing this up. We've noticed this before but never really dug in. I think we can fix it by going of npm username rather than email addresses.

**Comment by pgengler** [comment]
This should be fixed now. The NPM maintainer stuff is now based just on username, instead of username+email address.

**Comment by null-null-null** [comment]
Thanks for working on that over the holidays! Everything seems to be working now.
