### ISSUE TITLE
Getting redirected to not-found page

### ISSUE THREAD

**Issue by blessenm** [emberobserver/client#28]
I just tried browsing through the addons and I cant seem to get any of the addon pages. When I click on an addon from a category I get redirected to the 'not-found' page.

Even when I try to go to a url like `http://emberobserver.com/addons/ember-cli-document-title`, I get the same result.

**Comment by kategengler** [comment]
What browser/OS? I haven't seen this happen so I wonder if it's environment dependent. 

Going to '/not-found' is the `error` action on the addon/show route. Can you use the Ember Inspector to see if any promises rejected?

**Comment by blessenm** [comment]
Im sorry. I should've investigated first. I see that my companies websense proxy is blocking the api call to http://emberobserver.com/api/addons?name=ember-cli-document-title. So I think the code fails as the proxy is returning html when its expecting json.

But the web page and other api calls are working fine so I wrongly assumed something maybe wrong with the app. I am closing this issue.

**Comment by kategengler** [comment]
No problem, it's definitely odd that that one request would be different. I guess the proxy could treat it differently because of the querystring.
