### ISSUE TITLE
Default Badge

### ISSUE THREAD

**Issue by knownasilya** [emberobserver/client#29]
Would be awesome if the badge could render a badge that says `ember observer | ...` or something similar for addons that haven't yet been processed completely.

**Comment by pgengler** [comment]
There is a default badge for addons that haven't been reviewed yet; it shows 'n/a' in place of the sore and looks like this:
![Ember Observer N/A badge](http://images.pgengler.net/ember-observer-na-badge.svg)

**Comment by knownasilya** [comment]
I mean't more like if the addon hasn't made it to the system. For example: I published `ember-inline-component` yesterday, and the badge only showed up a few hours later. In the mean while, it was a broken image.

**Comment by kategengler** [comment]
It should be no more than an hour from publish -> badge (the frequency we pull from npm).
