### ISSUE TITLE
Search's typeahead/autocomplete breaks the web

### ISSUE THREAD

**Issue by jhr007** [emberobserver/client#31]
The TL;DR: 
I just want to "open-in-new-tab" addons shown in the search's type-ahead. 

My user-experience...  
I type something in the search box... the search feature shows a filtered list...  and I find a few addons match my intentions. I then middle-click an addon's line to open it in a new tab... but it doesn't open in a new tab. :sob: 

:grin:  "Breaks the web" is a tongue-in-cheek jab... I really do appreciate the "above-and-beyond" efforot that has been put into Ember Observer. 

Thank you.

**Comment by pgengler** [comment]
This is something we're going to be fixing soon. The autocomplete box wasn't originally intended to be used as a search, just a helper, so the current behavior made sense, but as you noted, it doesn't seem to make sense any more.

**Comment by jhr007** [comment]
:grinning: 
I guessed this was this case... Mostly created the ticket to make it explicit. I also noticed, pressing enter after typing chose the first search result instead of going to a search page. 
:+1:

**Comment by kategengler** [comment]
Just deployed a new search-ish thing that has results w/ a url.
