### ISSUE TITLE
Score for having more than 1 contributor includes `Tomster` commits

### ISSUE THREAD

**Issue by elwayman02** [emberobserver/client#36]
Any addon generated from the ember-cli blueprint will automatically receive a point for having more than 1 contributor, since it registers the initial commit as coming from [ember-tomster](https://github.com/ember-tomster). This devalues that particular part of the scoring system, although pointing it out will hurt the scores on several of my addons, heh... =P

**Comment by kategengler** [comment]
Good catch. Looks like this happened relatively recently when that account was registered. Totally explains a jump in points that I hadn't had a chance to look into yet.

**Comment by pgengler** [comment]
This should be fixed now.

**Comment by elwayman02** [comment]
@kategengler @pgengler at the risk of once again hurting my own scores (heh), I must point out that `greenkeeperio-bot` is not a real contributor:

https://github.com/elwayman02/ember-user-activity/graphs/contributors
https://emberobserver.com/addons/ember-user-activity

The solution might be to just keep a whitelist of bot contributors that includes Tomster and other known bots...I'm not sure.

**Comment by elwayman02** [comment]
Either that, or this is a continued indication that there isn't a lot of value to basing a binary score on whether a project has 1 contributor or 2+...perhaps reevaluating that part of the scoring system would make more sense than continuing to try and fix it.

**Comment by kategengler** [comment]
Filtering out one bot already; might as well make it two. 

The scoring based on # of contributors is supposed to be a proxy for sustainability (bus factor). A lot of options to solve this long term: we could up the # of contributors or maybe check for # of repeat contributors or any number of other things.

**Comment by elwayman02** [comment]
Maybe commit activity as a factor of time? I've known several projects that have 2 contributors that have far less sustainability than some 1 contributor projects. I know that's a contrived example to an extent, but I think something like # of commits or # of releases scaled to the lifetime of the project could be a better metric?

**Comment by kategengler** [comment]
It's really meant to be a proxy for sustainability in the sense that individual contributors get burnt out (I should know), change jobs, etc. It's also a proxy for whether or not the addon is being collaborated on. 

Activity is a different proxy and that's done with the # of commits in the last 3 months and the # of releases in the last 3 months.
