### ISSUE TITLE
Initial load slow in Firefox

### ISSUE THREAD

**Issue by simenheg** [emberobserver/client#41]
When entering https://emberobserver.com for the first time in Firefox, a white page is shown for 15-20  seconds. A reload of the page shows a white page for 5-6 seconds.

This problem is not as severe in Chrome, where the white page is only visible 2-3 seconds, for both the initial load and on reloads.

**Comment by jherdman** [comment]
Is this still true? I checked FF Developer Edition and everything seemed okay today.

**Comment by kategengler** [comment]
Correct -- this should have been fixed by a combination of move to smaller API requests + benefits of newer ember versions.

**Comment by simenheg** [comment]
Hi. I just retested this with Firefox 53 and I think you're right, it's much faster now. Thanks.
