### ISSUE TITLE
Search only does titles

### ISSUE THREAD

**Issue by csterritt** [emberobserver/client#6]
Hello -- trying to track down the "ember-paper" add-on, which is an implementation of the "Material Design" thing.  And, once I get to the Ember Observer page for ember-paper, it mentions Material.  However, typing in "material" into the "Find addons" box only shows addons with the word "material" in the name of the addon.

So, clearly "ember-paper" is misnamed :-)

Perhaps an "advanced search" button which allows searching descriptions as well?  Thanks!

**Comment by kategengler** [comment]
Definitely on the radar but lower priority. The 'Find addons' box is probably mislabeled too, as it is more of a 'Jump to addon, mantainer or category' box.

**Comment by kategengler** [comment]
Just deployed with a new search that looks at descriptions too. Also working on an advanced search with full-text searching of Readmes.
