### ISSUE TITLE
Revise sort criteria for Top addons

### ISSUE THREAD

**Issue by simonihmig** [emberobserver/client#84]
I would suggest to overthink the sorting criteria for the Top 10 / Top 100 list. 

Currently the list seems to be sorted by download count (ok, first probably by score, but most addons in the Top 100 have a ten, so that does not matter much). The problems with download count are
* it doesn't express actual user appreciation accurately, the vast majority of downloads certainly come from CI runs rather than users installing the addon
* that overly emphasizes addons that EmberCLI installs by default
* the download count caused by CI runs is heavily dependent on the CI setup: using yarn with its cache persisted across builds will cause very few downloads, while builds that download every time will cause a hit for every build and every ember-try scenario

As a consequence the list is headed by addons such as ember-cli-babel, loader.js or ember-resolver. So "infrastructure" addons that are essential to get EmberCLI up and running, but no user would ever ask himself, if he should or should not use them, they are simply required.

So at least the Top 10 list yields very limited value IMHO. No optional addon, no matter how popular it is, would ever have the change to reach the no. 1 spot. But if this list should give a new user some guidance into addons that are hugely popular with the community, and which he should have a look at to build something great, this list I think should be headed by things like **e-concurrency, liquid-fire, mirage, e-i18n** et al. (none of which show up in the Top 10 currently)

The solution I would propose is to just change the sorting based on **Github stars**. I think this would overcome most of the mentioned problems, i.e. much more closely reflect how much real humans value them instead of machines (Travis). And it does not require a somewhat artificial distinction between default and optional addons. Those "infrastructure" addons like loader.js would naturally move down the list, while the Top 10 would probably much more resemble the one I would expect to see (see the previous paragraph). 

In my opinion, that would serve the needs of users seeking guidance and orientation much more than the current solution (and is probably very easy to implement). And as emberobserver.com is the first address for users to search for some good addons, it would further improve the great service it offers to the community! My 2¢ 🙂

**Comment by kategengler** [comment]
Correct, it currently sorts by score, download count in the last month. I agree download count is an unideal metric, but github stars also have problems. Github stars hardly ever decrease, so the place in the top 100 would be dominated by the oldest repos, rather than those with momentum.

One plan I have is to remove the addons that install by default from the top list into a separate list. I also have further out plans to replace the downloads popularity metric with a reporting addon.

**Comment by simonihmig** [comment]
> Github stars hardly ever decrease, so the place in the top 100 would be dominated by the oldest repos, rather than those with momentum.

Good point! Agree that it has its drawbacks, but still as a short-term solution (that is *presumably* easy to implement) I think it would still be a relevant improvement!?

**Comment by kategengler** [comment]
I don't agree. It would be dominated by older addons that aren't necessarily good recommendations at this point.

**Comment by simonihmig** [comment]
@kategengler Is that really true? Is there a way to see how that list would look like? 

When I wrote this issue I checked the mentioned addons *I* would expect to see in the Top 10 (like e-concurrency, liquid-fire, mirage, e-i18n), and they indeed had very high star counts. Do you have any examples of such older addons with high scores that you would not "like" to see at the top (very subjective of course)?

**Comment by kategengler** [comment]
Looking at the list of addons sorted by Score, Github stars, the top 10
would not include any of the ones you listed. I have also considered
curating the top 100, but honestly wouldn't ever consider sorting by Github
stars.

**Comment by simonihmig** [comment]
> Looking at the list of addons sorted by Score

You see that in your internal database, or how? There is no way to see this by myself, right?

**Comment by kategengler** [comment]
Database; it's not something available through the API.

**Comment by simonihmig** [comment]
@kategengler Ok, closing this then. Thanks for your feedback anyways, appreciate it! Hope you can come up with something better! 😉
